[package]
name = "xplm_egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.16"
glow = "0.11"
xplm = { path = "../rust-xplm" }
memoffset = "0.6"
